-- MySQL Script generated by MySQL Workbench
-- Thu Nov  9 15:54:10 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema jats
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `jats` ;

-- -----------------------------------------------------
-- Schema jats
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jats` DEFAULT CHARACTER SET utf8 ;
USE `jats` ;

-- -----------------------------------------------------
-- Table `jats`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jats`.`USER` (
  `Username` VARCHAR(32) NOT NULL,
  `PasswordHash` CHAR(64) NOT NULL COMMENT '64 hex chars to store SHA256 hash',
  `Fname` VARCHAR(16) NULL,
  `Lname` VARCHAR(16) NULL,
  `IsActive` TINYINT NOT NULL DEFAULT 1 COMMENT 'Data type TINYINT == BOOLEAN, 0 == FALSE',
  PRIMARY KEY (`Username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jats`.`APPLICANT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jats`.`APPLICANT` (
  `Username` VARCHAR(32) NOT NULL,
  `Education` TINYTEXT NULL,
  PRIMARY KEY (`Username`),
  CONSTRAINT `ApplicantFK_Username`
    FOREIGN KEY (`Username`)
    REFERENCES `jats`.`USER` (`Username`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jats`.`APPLICANT_EXPERIENCE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jats`.`APPLICANT_EXPERIENCE` (
  `ApplicantUsername` VARCHAR(32) NOT NULL,
  `Experience` VARCHAR(32) NOT NULL,
  `ExperienceDesc` TINYTEXT NULL COMMENT 'Optional longer description of experience',
  PRIMARY KEY (`ApplicantUsername`, `Experience`),
  CONSTRAINT `ExperienceFK_Username`
    FOREIGN KEY (`ApplicantUsername`)
    REFERENCES `jats`.`APPLICANT` (`Username`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jats`.`APPLICANT_PROJECT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jats`.`APPLICANT_PROJECT` (
  `ApplicantUsername` VARCHAR(32) NOT NULL,
  `Project` VARCHAR(32) NOT NULL,
  `ProjectDesc` TINYTEXT NULL COMMENT 'Optional longer description of project',
  PRIMARY KEY (`ApplicantUsername`, `Project`),
  CONSTRAINT `ProjectFK_Username`
    FOREIGN KEY (`ApplicantUsername`)
    REFERENCES `jats`.`APPLICANT` (`Username`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jats`.`APPLICANT_CERTIFICATION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jats`.`APPLICANT_CERTIFICATION` (
  `ApplicantUsername` VARCHAR(32) NOT NULL,
  `Certification` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`ApplicantUsername`, `Certification`),
  CONSTRAINT `CertificationFK_Username`
    FOREIGN KEY (`ApplicantUsername`)
    REFERENCES `jats`.`APPLICANT` (`Username`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jats`.`APPLICANT_SKILL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jats`.`APPLICANT_SKILL` (
  `ApplicantUsername` VARCHAR(32) NOT NULL,
  `Skill` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`ApplicantUsername`, `Skill`),
  CONSTRAINT `SkillFK_Username`
    FOREIGN KEY (`ApplicantUsername`)
    REFERENCES `jats`.`APPLICANT` (`Username`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jats`.`APPLICANT_COMPETITION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jats`.`APPLICANT_COMPETITION` (
  `ApplicantUsername` VARCHAR(32) NOT NULL,
  `Competition` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`ApplicantUsername`, `Competition`),
  CONSTRAINT `CompetitionFK_Username`
    FOREIGN KEY (`ApplicantUsername`)
    REFERENCES `jats`.`APPLICANT` (`Username`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jats`.`ADMIN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jats`.`ADMIN` (
  `Username` VARCHAR(32) NOT NULL,
  `DeveloperFlag` TINYINT NOT NULL DEFAULT 0 COMMENT 'Data type TINYINT == BOOLEAN, 0 == FALSE',
  `DeveloperType` VARCHAR(32) NULL,
  PRIMARY KEY (`Username`),
  CONSTRAINT `AdminFK_Username`
    FOREIGN KEY (`Username`)
    REFERENCES `jats`.`USER` (`Username`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jats`.`PERMISSION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jats`.`PERMISSION` (
  `PermissionLevel` INT NOT NULL,
  PRIMARY KEY (`PermissionLevel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jats`.`PERMISSION_ABILITY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jats`.`PERMISSION_ABILITY` (
  `PermissionLevel` INT NOT NULL,
  `Ability` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`PermissionLevel`, `Ability`),
  CONSTRAINT `PermAbilityFK_PermissionLevel`
    FOREIGN KEY (`PermissionLevel`)
    REFERENCES `jats`.`PERMISSION` (`PermissionLevel`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jats`.`ADMIN_HAS_PERM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jats`.`ADMIN_HAS_PERM` (
  `AdminUsername` VARCHAR(32) NOT NULL,
  `PermLevel` INT NOT NULL,
  PRIMARY KEY (`AdminUsername`, `PermLevel`),
  INDEX `AdminHasPermFK_PermLevel_idx` (`PermLevel` ASC) VISIBLE,
  CONSTRAINT `AdminHasPermFK_AdminUsername`
    FOREIGN KEY (`AdminUsername`)
    REFERENCES `jats`.`ADMIN` (`Username`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `AdminHasPermFK_PermLevel`
    FOREIGN KEY (`PermLevel`)
    REFERENCES `jats`.`PERMISSION` (`PermissionLevel`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jats`.`ADMIN_RESPONSIBILITY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jats`.`ADMIN_RESPONSIBILITY` (
  `AdminUsername` VARCHAR(32) NOT NULL,
  `Responsibility` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`AdminUsername`, `Responsibility`),
  CONSTRAINT `ResponsibilityFK_AdminUsername`
    FOREIGN KEY (`AdminUsername`)
    REFERENCES `jats`.`ADMIN` (`Username`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jats`.`DEV_SPECIALIZATION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jats`.`DEV_SPECIALIZATION` (
  `AdminUsername` VARCHAR(32) NOT NULL,
  `Specialization` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`AdminUsername`, `Specialization`),
  CONSTRAINT `SpecializationFK_AdminUsername`
    FOREIGN KEY (`AdminUsername`)
    REFERENCES `jats`.`ADMIN` (`Username`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jats`.`APPLICATION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jats`.`APPLICATION` (
  `ApplicantUsername` VARCHAR(32) NOT NULL,
  `AName` VARCHAR(32) NOT NULL,
  `Notes` TINYTEXT NULL,
  `DateSubmitted` DATE NULL,
  `Status` VARCHAR(32) NULL,
  PRIMARY KEY (`ApplicantUsername`, `AName`),
  UNIQUE INDEX `ApplicantUsernamePK` (`ApplicantUsername` ASC),
  UNIQUE INDEX `ANamePK` (`AName` ASC),
  CONSTRAINT `ApplicationFK_Username`
    FOREIGN KEY (`ApplicantUsername`)
    REFERENCES `jats`.`APPLICANT` (`Username`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jats`.`INTERVIEW`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jats`.`INTERVIEW` (
  `InterviewID` INT NOT NULL AUTO_INCREMENT,
  `ApplicantUsername` VARCHAR(32) NOT NULL,
  `Stage` VARCHAR(32) NULL,
  `DateTime` DATETIME NOT NULL,
  `ApplicationName` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`InterviewID`, `ApplicantUsername`),
  CONSTRAINT `InterviewFK_Username`
    FOREIGN KEY (`ApplicantUsername`)
    REFERENCES `jats`.`APPLICANT` (`Username`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `InterviewFK_Application`
    FOREIGN KEY (`ApplicationName`)
    REFERENCES `jats`.`APPLICATION` (`AName`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    INDEX `InterviewFK_Username_idx` (`ApplicantUsername` ASC) VISIBLE,
	INDEX `InterviewFK_Application_idx` (`ApplicationName` ASC) VISIBLE
    )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jats`.`DOCUMENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jats`.`DOCUMENT` (
  `ApplicantUsername` VARCHAR(32) NOT NULL,
  `DocFileName` VARCHAR(32) NOT NULL,
  `DocType` VARCHAR(32) NULL,
  `Description` TINYTEXT NULL,
  PRIMARY KEY (`ApplicantUsername`, `DocFileName`),
  UNIQUE INDEX `DocFileNamePK` (`DocFileName` ASC),
  CONSTRAINT `DocumentFK_Username`
    FOREIGN KEY (`ApplicantUsername`)
    REFERENCES `jats`.`APPLICANT` (`Username`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jats`.`APPL_RELEVANT_URL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jats`.`APPL_RELEVANT_URL` (
  `ApplicantUsername` VARCHAR(32) NOT NULL,
  `AName` VARCHAR(32) NOT NULL,
  `RelevantURL` VARCHAR(512) NOT NULL,
  PRIMARY KEY (`ApplicantUsername`, `AName`, `RelevantURL`),
  INDEX `RelevantUrlFK_AName_idx` (`AName` ASC) VISIBLE,
  CONSTRAINT `RelevantUrlFK_Username`
    FOREIGN KEY (`ApplicantUsername`)
    REFERENCES `jats`.`APPLICANT` (`Username`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `RelevantUrlFK_AName`
    FOREIGN KEY (`AName`)
    REFERENCES `jats`.`APPLICATION` (`AName`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jats`.`APPL_CATEGORY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jats`.`APPL_CATEGORY` (
  `ApplicantUsername` VARCHAR(32) NOT NULL,
  `AName` VARCHAR(32) NOT NULL,
  `Category` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`ApplicantUsername`, `AName`, `Category`),
  INDEX `ApplCategoryFK_AName_idx` (`AName` ASC) VISIBLE,
  CONSTRAINT `ApplCategoryFK_Username`
    FOREIGN KEY (`ApplicantUsername`)
    REFERENCES `jats`.`APPLICANT` (`Username`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ApplCategoryFK_AName`
    FOREIGN KEY (`AName`)
    REFERENCES `jats`.`APPLICATION` (`AName`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jats`.`COMPANY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jats`.`COMPANY` (
  `CompanyName` VARCHAR(64) NOT NULL,
  `Industry` VARCHAR(32) NULL,
  `HomePageURL` TINYTEXT NULL,
  `Description` TINYTEXT NULL,
  PRIMARY KEY (`CompanyName`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jats`.`JOB`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jats`.`JOB` (
  `CompName` VARCHAR(64) NOT NULL,
  `PositionName` VARCHAR(64) NOT NULL,
  `Description` MEDIUMTEXT NULL COMMENT 'MEDIUMTEXT data type since some descriptions are very long',
  `JobPostFile` VARCHAR(32) NULL,
  `PositionType` VARCHAR(32) NULL,
  `ApplicationDeadline` DATE NOT NULL,
  `Salary` DECIMAL(10,2) NULL,
  PRIMARY KEY (`CompName`, `PositionName`),
  UNIQUE INDEX `PositionNamePK` (`PositionName` ASC),
  CONSTRAINT `JobFK_CompName`
    FOREIGN KEY (`CompName`)
    REFERENCES `jats`.`COMPANY` (`CompanyName`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jats`.`JOB_QUALIFICATION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jats`.`JOB_QUALIFICATION` (
  `CompanyName` VARCHAR(64) NOT NULL,
  `PositionName` VARCHAR(64) NOT NULL,
  `Qualification` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`CompanyName`, `PositionName`, `Qualification`),
  INDEX `JobQualFK_PositionName_idx` (`PositionName` ASC) VISIBLE,
  CONSTRAINT `JobQualFK_CompanyName`
    FOREIGN KEY (`CompanyName`)
    REFERENCES `jats`.`COMPANY` (`CompanyName`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `JobQualFK_PositionName`
    FOREIGN KEY (`PositionName`)
    REFERENCES `jats`.`JOB` (`PositionName`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jats`.`JOB_RESPONSIBILITY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jats`.`JOB_RESPONSIBILITY` (
  `CompanyName` VARCHAR(64) NOT NULL,
  `PositionName` VARCHAR(64) NOT NULL,
  `Responsibility` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`CompanyName`, `PositionName`, `Responsibility`),
  INDEX `JobResFK_PositionName_idx` (`PositionName` ASC) VISIBLE,
  CONSTRAINT `JobResFK_CompanyName`
    FOREIGN KEY (`CompanyName`)
    REFERENCES `jats`.`COMPANY` (`CompanyName`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `JobResFK_PositionName`
    FOREIGN KEY (`PositionName`)
    REFERENCES `jats`.`JOB` (`PositionName`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jats`.`OFFER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jats`.`OFFER` (
  `ApplicantUsername` VARCHAR(32) NOT NULL,
  `OfferFileName` VARCHAR(32) NOT NULL,
  `ResponseDeadline` DATETIME NOT NULL,
  `Compensation` DECIMAL(10,2) NULL,
  `StartDate` DATE NULL,
  `Notes` TINYTEXT NULL,
  `CompName` VARCHAR(64) NOT NULL,
  `PosName` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`ApplicantUsername`, `OfferFileName`),
  INDEX `OfferFK_CompName_idx` (`CompName` ASC) VISIBLE,
  INDEX `OfferFK_PosName_idx` (`PosName` ASC) VISIBLE,
  CONSTRAINT `OfferFK_CompName`
    FOREIGN KEY (`CompName`)
    REFERENCES `jats`.`COMPANY` (`CompanyName`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `OfferFK_PosName`
    FOREIGN KEY (`PosName`)
    REFERENCES `jats`.`JOB` (`PositionName`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jats`.`CONTACT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jats`.`CONTACT` (
  `ContactID` INT NOT NULL AUTO_INCREMENT,
  `LinkedInURL` VARCHAR(64) NULL,
  `Fname` VARCHAR(16) NOT NULL,
  `Lname` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`ContactID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jats`.`CONTACT_EMAIL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jats`.`CONTACT_EMAIL` (
  `ContactID` INT NOT NULL,
  `Email` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`ContactID`, `Email`),
  CONSTRAINT `ContactEmailFK_ContactID`
    FOREIGN KEY (`ContactID`)
    REFERENCES `jats`.`CONTACT` (`ContactID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jats`.`CONTACT_PHONE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jats`.`CONTACT_PHONE` (
  `ContactID` INT NOT NULL,
  `Phone` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`Phone`, `ContactID`),
  INDEX `ContactPhoneFK_ContactID_idx` (`ContactID` ASC) VISIBLE,
  CONSTRAINT `ContactPhoneFK_ContactID`
    FOREIGN KEY (`ContactID`)
    REFERENCES `jats`.`CONTACT` (`ContactID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jats`.`REFERRAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jats`.`REFERRAL` (
  `ReferralID` INT NOT NULL AUTO_INCREMENT,
  `ContID` INT NOT NULL,
  `Date` DATE NULL,
  `Notes` TINYTEXT NULL,
  `ApplicantUsername` VARCHAR(32) NOT NULL,
  `CompName` VARCHAR(64) NOT NULL,
  `PosName` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`ReferralID`, `ContID`),
  INDEX `ReferralFK_Username_idx` (`ApplicantUsername` ASC) VISIBLE,
  INDEX `ReferralFK_CompName_idx` (`CompName` ASC) VISIBLE,
  INDEX `ReferralFK_PosName_idx` (`PosName` ASC) VISIBLE,
  CONSTRAINT `ReferralFK_ContID`
    FOREIGN KEY (`ContID`)
    REFERENCES `jats`.`CONTACT` (`ContactID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ReferralFK_Username`
    FOREIGN KEY (`ApplicantUsername`)
    REFERENCES `jats`.`APPLICANT` (`Username`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ReferralFK_CompName`
    FOREIGN KEY (`CompName`)
    REFERENCES `jats`.`COMPANY` (`CompanyName`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ReferralFK_PosName`
    FOREIGN KEY (`PosName`)
    REFERENCES `jats`.`JOB` (`PositionName`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jats`.`MENTIONS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jats`.`MENTIONS` (
  `ApplicantUsername` VARCHAR(32) NOT NULL,
  `InterID` INT NOT NULL,
  `CompName` VARCHAR(64) NOT NULL,
  `PosName` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`ApplicantUsername`, `InterID`, `CompName`, `PosName`),
  INDEX `MentionsFK_InterID_idx` (`InterID` ASC) VISIBLE,
  INDEX `MentionsFK_CompName_idx` (`CompName` ASC) VISIBLE,
  INDEX `MentionsFK_PosName_idx` (`PosName` ASC) VISIBLE,
  CONSTRAINT `MentionsFK_Username`
    FOREIGN KEY (`ApplicantUsername`)
    REFERENCES `jats`.`APPLICANT` (`Username`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `MentionsFK_InterID`
    FOREIGN KEY (`InterID`)
    REFERENCES `jats`.`INTERVIEW` (`InterviewID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `MentionsFK_CompName`
    FOREIGN KEY (`CompName`)
    REFERENCES `jats`.`COMPANY` (`CompanyName`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `MentionsFK_PosName`
    FOREIGN KEY (`PosName`)
    REFERENCES `jats`.`JOB` (`PositionName`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jats`.`CORRESPONDS_TO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jats`.`CORRESPONDS_TO` (
  `ApplicantUsername` VARCHAR(32) NOT NULL,
  `ApplicationName` VARCHAR(32) NOT NULL,
  `CompName` VARCHAR(64) NOT NULL,
  `PosName` VARCHAR(64) NOT NULL,
  `JobPostURL` TINYTEXT NULL,
  PRIMARY KEY (`ApplicantUsername`, `ApplicationName`, `CompName`, `PosName`),
  INDEX `CorrespondsFK_AName_idx` (`ApplicationName` ASC) VISIBLE,
  INDEX `CorrespondsFK_CompName_idx` (`CompName` ASC) VISIBLE,
  INDEX `CorrespondsFK_PosName_idx` (`PosName` ASC) VISIBLE,
  CONSTRAINT `CorrespondsFK_Username`
    FOREIGN KEY (`ApplicantUsername`)
    REFERENCES `jats`.`APPLICANT` (`Username`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `CorrespondsFK_AName`
    FOREIGN KEY (`ApplicationName`)
    REFERENCES `jats`.`APPLICATION` (`AName`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `CorrespondsFK_CompName`
    FOREIGN KEY (`CompName`)
    REFERENCES `jats`.`COMPANY` (`CompanyName`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `CorrespondsFK_PosName`
    FOREIGN KEY (`PosName`)
    REFERENCES `jats`.`JOB` (`PositionName`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jats`.`SUBMIT_WITH`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jats`.`SUBMIT_WITH` (
  `ApplicantUsername` VARCHAR(32) NOT NULL,
  `DocFile` VARCHAR(32) NOT NULL,
  `ApplicationName` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`ApplicantUsername`, `DocFile`, `ApplicationName`),
  INDEX `SubmitFK_DocFile_idx` (`DocFile` ASC) VISIBLE,
  INDEX `SubmitFK_AName_idx` (`ApplicationName` ASC) VISIBLE,
  CONSTRAINT `SubmitFK_Username`
    FOREIGN KEY (`ApplicantUsername`)
    REFERENCES `jats`.`APPLICANT` (`Username`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `SubmitFK_DocFile`
    FOREIGN KEY (`DocFile`)
    REFERENCES `jats`.`DOCUMENT` (`DocFileName`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `SubmitFK_AName`
    FOREIGN KEY (`ApplicationName`)
    REFERENCES `jats`.`APPLICATION` (`AName`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jats`.`TRACKS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jats`.`TRACKS` (
  `ApplicantUsername` VARCHAR(32) NOT NULL,
  `CompName` VARCHAR(64) NOT NULL,
  `PosName` VARCHAR(64) NOT NULL,
  `Notes` TINYTEXT NULL,
  `DateToApply` DATE NULL,
  PRIMARY KEY (`ApplicantUsername`, `CompName`, `PosName`),
  INDEX `TracksFK_CompName_idx` (`CompName` ASC) VISIBLE,
  INDEX `TracksFK_PosName_idx` (`PosName` ASC) VISIBLE,
  CONSTRAINT `TracksFK_Username`
    FOREIGN KEY (`ApplicantUsername`)
    REFERENCES `jats`.`APPLICANT` (`Username`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `TracksFK_CompName`
    FOREIGN KEY (`CompName`)
    REFERENCES `jats`.`COMPANY` (`CompanyName`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `TracksFK_PosName`
    FOREIGN KEY (`PosName`)
    REFERENCES `jats`.`JOB` (`PositionName`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jats`.`WORKS_AT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jats`.`WORKS_AT` (
  `CompName` VARCHAR(64) NOT NULL,
  `ContID` INT NOT NULL,
  `Role` VARCHAR(64) NULL,
  PRIMARY KEY (`CompName`, `ContID`),
  INDEX `WorksAtFK_ContID_idx` (`ContID` ASC) VISIBLE,
  CONSTRAINT `WorksAtFK_CompName`
    FOREIGN KEY (`CompName`)
    REFERENCES `jats`.`COMPANY` (`CompanyName`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `WorksAtFK_ContID`
    FOREIGN KEY (`ContID`)
    REFERENCES `jats`.`CONTACT` (`ContactID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jats`.`KNOWS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jats`.`KNOWS` (
  `ContID` INT NOT NULL,
  `ApplicantUsername` VARCHAR(32) NOT NULL,
  `Relationship` VARCHAR(32) NULL,
  `Notes` TINYTEXT NULL,
  `LastContactDate` DATE NULL,
  PRIMARY KEY (`ContID`, `ApplicantUsername`),
  INDEX `KnowsFK_Username_idx` (`ApplicantUsername` ASC) VISIBLE,
  CONSTRAINT `KnowsFK_ContID`
    FOREIGN KEY (`ContID`)
    REFERENCES `jats`.`CONTACT` (`ContactID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `KnowsFK_Username`
    FOREIGN KEY (`ApplicantUsername`)
    REFERENCES `jats`.`APPLICANT` (`Username`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jats`.`ATTENDS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jats`.`ATTENDS` (
  `ContID` INT NOT NULL,
  `ApplicantUsername` VARCHAR(32) NOT NULL,
  `InterID` INT NOT NULL,
  PRIMARY KEY (`ContID`, `ApplicantUsername`, `InterID`),
  INDEX `AttendsFK_Username_idx` (`ApplicantUsername` ASC) VISIBLE,
  INDEX `AttendsFK_InterID_idx` (`InterID` ASC) VISIBLE,
  CONSTRAINT `AttendsFK_ContID`
    FOREIGN KEY (`ContID`)
    REFERENCES `jats`.`CONTACT` (`ContactID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `AttendsFK_Username`
    FOREIGN KEY (`ApplicantUsername`)
    REFERENCES `jats`.`APPLICANT` (`Username`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `AttendsFK_InterID`
    FOREIGN KEY (`InterID`)
    REFERENCES `jats`.`INTERVIEW` (`InterviewID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
